### ISSUE TITLE
Debug in ProtocolGame::writeToOutputBuffer(NetworkMessage const&) ()

### ISSUE THREAD

**Issue by Seitron** [Johncorex/OTG-Premium-Version#81]
Aconteceu 2 vezes essa semana, alguem sabe alguma solução?

2020-11-06 00:36:58 -  Thread 2 "tfs" received signal SIGSEGV, Segmentation fault.
2020-11-06 00:36:58 -  [Switching to Thread 0x7ffff5bae700 (LWP 296872)]
2020-11-06 00:36:58 -  0x000055555565f6b8 in ProtocolGame::writeToOutputBuffer(NetworkMessage const&) ()

2020-11-06 00:36:58 -  Thread 2 (Thread 0x7ffff5bae700 (LWP 296872)):
2020-11-06 00:36:58 -  #0  0x000055555565f6b8 in ProtocolGame::writeToOutputBuffer(NetworkMessage const&) ()
2020-11-06 00:36:58 -  No symbol table info available.
2020-11-06 00:36:58 -  #1  0x000055555565682a in ProtocolGame::sendTextMessage(TextMessage const&) ()
2020-11-06 00:36:58 -  No symbol table info available.
2020-11-06 00:36:58 -  #2  0x00005555556c42ba in LuaScriptInterface::luaPlayerSendTextMessage(lua_State*) ()
2020-11-06 00:36:58 -  No symbol table info available.
2020-11-06 00:36:58 -  #3  0x00007ffff7667fb7 in ?? () from /lib/x86_64-linux-gnu/libluajit-5.1.so.2
2020-11-06 00:36:58 -  No symbol table info available.
2020-11-06 00:36:58 -  #4  0x00007ffff76b64a4 in lua_pcall () from /lib/x86_64-linux-gnu/libluajit-5.1.so.2
2020-11-06 00:36:58 -  No symbol table info available.
2020-11-06 00:36:58 -  #5  0x0000555555721f90 in LuaScriptInterface::protectedCall(lua_State*, int, int) ()
2020-11-06 00:36:58 -  No symbol table info available.
2020-11-06 00:36:58 -  #6  0x0000555555722d0f in LuaScriptInterface::callFunction(int) ()
2020-11-06 00:36:58 -  No symbol table info available.
2020-11-06 00:36:58 -  #7  0x00005555556ac043 in LuaEnvironment::executeTimerEvent(unsigned int) ()
2020-11-06 00:36:58 -  No symbol table info available.
2020-11-06 00:36:58 -  #8  0x0000555555627cc3 in Dispatcher::threadMain() ()
2020-11-06 00:36:58 -  No symbol table info available.
2020-11-06 00:36:58 -  #9  0x00007ffff70e4d84 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
2020-11-06 00:36:58 -  No symbol table info available.
2020-11-06 00:36:58 -  #10 0x00007ffff71f8609 in start_thread (arg=<optimized out>) at pthread_create.c:477
2020-11-06 00:36:58 -          ret = <optimized out>
2020-11-06 00:36:58 -          pd = <optimized out>
2020-11-06 00:36:58 -          unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140737316054784, 7736962354734757079, 140737488348046, 140737488348047, 140737488348048, 140737316052864, -7736940956107606825, -7736946132971227945}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
2020-11-06 00:36:58 -          not_first_call = 0
2020-11-06 00:36:58 -  #11 0x00007ffff7ef1293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
2020-11-06 00:36:58 -  No locals.

**Comment by Seitron** [comment]
Como não deu mais, ignora por um tempo
